src/objects/sked_Job_Offer__c.object
<CustomObject>
    <fields>
        <fullName>sked_Estimated_Distance__c</fullName>
        <label>Estimated Distance</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Estimated_Travel_Time__c</fullName>
        <label>Estimated Travel Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Job__c</fullName>
        <label>Job</label>
        <referenceTo>sked__Job__c</referenceTo>
        <relationshipLabel>Job Offers</relationshipLabel>
        <relationshipName>sked_Job_Offers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sked_Resource__c</fullName>
        <label>Resource</label>
        <referenceTo>sked__Resource__c</referenceTo>
        <relationshipLabel>Job Offers</relationshipLabel>
        <relationshipName>sked_Job_Offers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sked_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Offered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job Offer</label>
    <nameField>
        <displayFormat>JO-{000000}</displayFormat>
        <label>Job Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/skedJobOfferHandler.cls
public class skedJobOfferHandler {
    
    public static void afterUpdate(List<sked_Job_Offer__c> newRecords, Map<Id, sked_Job_Offer__c> updatedRecords) {
        onOfferAccepted(newRecords, updatedRecords);
    }

    private static void onOfferAccepted(List<sked_Job_Offer__c> newRecords, Map<Id, sked_Job_Offer__c> updatedRecords) {
    	List<sked_Job_Offer__c> acceptedOffers = new List<sked_Job_Offer__c>();
    	Set<Id> jobIds = new Set<Id>();
    	for (sked_Job_Offer__c newRecord : newRecords) {
    		sked_Job_Offer__c oldData = updatedRecords.get(newRecord.Id);
    		if (newRecord.sked_Status__c != oldData.sked_Status__c && newRecord.sked_Status__c == skedConstants.JOB_OFFER_STATUS_ACCEPTED) {
    			acceptedOffers.add(newRecord);
    			jobIds.add(newRecord.sked_Job__c);
    		}
    	}
    	if (!acceptedOffers.isEmpty()) {
    		List<sked__Job_Allocation__c> newSkedAllocations = new List<sked__Job_Allocation__c>();
    		for (sked_Job_Offer__c acceptedOffer : acceptedOffers) {
    			sked__Job_Allocation__c skedAllocation = new sked__Job_Allocation__c(
    				sked__Job__c = acceptedOffer.sked_Job__c,
    				sked__Resource__c = acceptedOffer.sked_Resource__c,
    				sked__Status__c = skedConstants.JOB_ALLOCATION_STATUS_CONFIRMED,
                    sked__Estimated_Travel_Time__c = acceptedOffer.sked_Estimated_Travel_Time__c,
                    sked_Estimated_Distance__c = acceptedOffer.sked_Estimated_Distance__c
				);
				newSkedAllocations.add(skedAllocation);
    		}
    		insert newSkedAllocations;
    	}
    }
    
}