src/objects/sked_Medication__c.object
<CustomObject>
    <fields>
        <fullName>sked_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Dosage__c</fullName>
        <label>Dosage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sked_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sked_Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sked_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Medication</relationshipLabel>
        <relationshipName>sked_Medication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sked_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sked_Support_Plan__c</fullName>
        <label>Support Plan</label>
        <referenceTo>sked_Support_Plan__c</referenceTo>
        <relationshipLabel>sked_Medication</relationshipLabel>
        <relationshipName>sked_Medication</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Medication</label>
    <nameField>
        <label>Medication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medication</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/sked_Must_Read_Information__c.object
<CustomObject>
    <fields>
        <fullName>sked_Information__c</fullName>
        <label>Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sked_Support_Plan__c</fullName>
        <label>Support Plan</label>
        <referenceTo>sked_Support_Plan__c</referenceTo>
        <relationshipLabel>Must Read Information</relationshipLabel>
        <relationshipName>sked_Must_Read_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Must Read Information</label>
    <nameField>
        <label>Must Read Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Must Read Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/sked_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>sked_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sked_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outcomes</relationshipLabel>
        <relationshipName>sked_Outcomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sked_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sked_Progress_Notes__c</fullName>
        <label>Outcome Progress</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sked_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Making Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Making Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ended</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>sked_Support_Plan__c</fullName>
        <label>Support Plan</label>
        <referenceTo>sked_Support_Plan__c</referenceTo>
        <relationshipLabel>Outcomes</relationshipLabel>
        <relationshipName>sked_Outcomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Outcome</label>
    <nameField>
        <label>Outcome Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/sked_Support_Guidance__c.object
<CustomObject>
    <fields>
        <fullName>sked_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sked_Guidance_Information__c</fullName>
        <label>Guidance Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>sked_Support_Plan__c</fullName>
        <label>Support Plan</label>
        <referenceTo>sked_Support_Plan__c</referenceTo>
        <relationshipLabel>Support Guidance</relationshipLabel>
        <relationshipName>sked_Support_Guidance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Support Guidance</label>
    <nameField>
        <label>Support Guidance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Guidance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/sked_Support_Plan__c.object
<CustomObject>
    <fields>
        <fullName>sked_Achieving_Score__c</fullName>
        <label>Achieving Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Achieving__c</fullName>
        <inlineHelpText>Being supported and guided in their learning and in the development of their skills, confidence and self-esteem at home, at school and in the community</inlineHelpText>
        <label>Achieving</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Active_SHANARRI__c</fullName>
        <inlineHelpText>Having opportunities to take part in activities such as play, recreation and sport which contribute to healthy growth and development both at home and in the community</inlineHelpText>
        <label>Active</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Active_Score__c</fullName>
        <label>Active Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sked_Healthy_Score__c</fullName>
        <label>Healthy Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Healthy__c</fullName>
        <inlineHelpText>Having the highest attainable standards of physical and mental health, access to suitable healthcare, and support in learning to make healthy and safe choices</inlineHelpText>
        <label>Healthy</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_How_my_support_is_structured__c</fullName>
        <inlineHelpText>times/length of stay/staff ratio</inlineHelpText>
        <label>How my support is structured?</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Included_Score__c</fullName>
        <label>Included Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Included__c</fullName>
        <inlineHelpText>Having help to overcome social, educational, physical and economic inequalities and being accepted as part of the community in which they live and learn</inlineHelpText>
        <label>Included</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>sked_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Support Plans</relationshipLabel>
        <relationshipName>Support_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sked_Nurtured_Score__c</fullName>
        <label>Nurtured Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Nurtured__c</fullName>
        <inlineHelpText>Having a nurturing place to live, in a family setting with additional help if needed or, where this is not possible, in a suitable care setting</inlineHelpText>
        <label>Nurtured</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Respected_Score__c</fullName>
        <label>Respected Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Respected__c</fullName>
        <inlineHelpText>Having the opportunity, along with carers to be heard and involved in decisions which affect them</inlineHelpText>
        <label>Respected</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Responsible_Score__c</fullName>
        <label>Responsible Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Responsible__c</fullName>
        <inlineHelpText>Having opportunities and encouragement o play active and responsible roles in their schools and communities and where necessary, having appropriate guidance and supervision and being involved in decisions that affect them</inlineHelpText>
        <label>Responsible</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Safe_Score__c</fullName>
        <label>Safe Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sked_Safe__c</fullName>
        <inlineHelpText>Protected from abuse, neglect or harm at home, at school and in the community</inlineHelpText>
        <label>Safe</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Support Plan</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Support Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Plans</pluralLabel>
    <recordTypes>
        <fullName>Child</fullName>
        <active>true</active>
        <description>Used for Child Support Plans - also enables SHANARRI</description>
        <label>Child</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/skedSupportPlanDeepCloneController.cls
public class skedSupportPlanDeepCloneController {

    //added an instance varaible for the standard controller
    private ApexPages.StandardController controller {get; set;}
     // add the instance for the variables being passed by id on the url
    private sked_Support_Plan__c supPlan {get;set;}
    // set the id of the record that is created -- ONLY USED BY THE TEST CLASS
    public ID newRecordId {get;set;}

    // initialize the controller
    public skedSupportPlanDeepCloneController(ApexPages.StandardController controller) {

        //initialize the stanrdard controller
        this.controller = controller;
        // load the current record
        supPlan = (sked_Support_Plan__c)controller.getRecord();

    }

    // method called from the VF's action attribute to clone the sp
    public PageReference cloneWithItems() {

         // setup the save point for rollback
         Savepoint sp = Database.setSavepoint();
         sked_Support_Plan__c newSP;

         try {
              //copy the Support Plan - ONLY INCLUDE THE FIELDS YOU WANT TO CLONE
             supPlan = [SELECT Id, 
                        		Name,
                        		sked_Individual__c,
                        		sked_How_my_support_is_structured__c,
                        		RecordTypeId,
                        		//SHANARRI FIELDS - Child Record Type
                        		sked_Safe_Score__c,
                        		sked_Safe__c,
                        		sked_Healthy_Score__c,
                        		sked_Healthy__c,
                        		sked_Active_Score__c,
                        		sked_Active_SHANARRI__c, 
                        		sked_Nurtured_Score__c,
                        		sked_Nurtured__c,
                        		sked_Achieving_Score__c,
                        		sked_Achieving__c,
                        		sked_Respected_Score__c,
                        		sked_Respected__c,
                        		sked_Responsible_Score__c,
                        		sked_Responsible__c,
                        		sked_Included_Score__c,
                        		sked_Included__c
                        FROM 	sked_Support_Plan__c 
                        WHERE 	Id = :supPlan.id];
             
             newSP = supPlan.clone(false);
             insert newSP;

             // set the id of the new sp created for testing
               newRecordId = newSP.id;

             // copy over the must read information line items
             List<sked_Must_Read_Information__c> mustreadinfo = new List<sked_Must_Read_Information__c>();
             for (sked_Must_Read_Information__c mr : [Select 
                                                 		mri.Id, 
                                                 		mri.Name,
                                                 		mri.sked_Information__c, 
                                                 		mri.sked_Support_Plan__c 
                                                 From 	sked_Must_Read_information__c mri 
                                                 where 	sked_Support_Plan__c = :supPlan.id]) {
                 
                  sked_Must_Read_Information__c newMRI = mr.clone(false);
                  newMRI.sked_Support_Plan__c = newSP.id;
                  mustreadinfo.add(newMRI);
             }
             insert mustreadinfo;
             
             // copy over the support guidance line items
            
             List<sked_Support_Guidance__c> supportguidance = new List<sked_Support_Guidance__c>();
             for (sked_Support_Guidance__c  sg : [Select 
                                                 	sup.Id, 
                                                 	sup.Name,
                                              		sup.sked_Guidance_Information__c,
                                             		sup.sked_Active__c
                                             From 	sked_Support_Guidance__c sup 
                                             where 	sked_Support_Plan__c = :supPlan.id]) {
                 
                  sked_Support_Guidance__c newSG = sg.clone(false);
                  newSG.sked_Support_Plan__c = newSP.id;
                  supportguidance.add(newSG);
             }
             insert supportguidance;
             
             // copy over the Outcome line items
            
             List<sked_Outcome__c> outcomes = new List<sked_Outcome__c>();
             for (sked_Outcome__c  ot : [Select 
                                            out.Id, 
                                            out.Name,
                                    		out.sked_Active__c,
                                    		out.sked_Contact__c,
                                    		out.sked_Description__c,
                                    		out.sked_End_Date__c, 
                                    		out.sked_Progress_Notes__c,
                                    		out.sked_Start_Date__c,
                                    		out.sked_Status__c
                                     From 	sked_Outcome__c out 
                                     where 	sked_Support_Plan__c  = :supPlan.id]) {
                 
                  sked_Outcome__c newOT = ot.clone(false);
                  newOT.sked_Support_Plan__c  = newSP.id;
                  outcomes.add(newOT);
             }
             insert outcomes;
             
            // copy over the Medication line items
            
             List<sked_Medication__c> medication = new List<sked_Medication__c>();
             for (sked_Medication__c  me : [Select 
                                            med.Id, 
                                            med.Name,
                                       		med.sked_Description__c, 
                                       		med.sked_Dosage__c,
                                       		med.sked_End_Date__c,
                                       		med.sked_Frequency__c,
                                       		med.sked_Individual__c,
                                       		med.sked_Start_Date__c
                                     From 	sked_Medication__c med 
                                     where 	sked_Support_Plan__c  = :supPlan.id]) {
                 
                  sked_Medication__c newME = me.clone(false);
                  newME.sked_Support_Plan__c  = newSP.id;
                  medication.add(newME);
             }
             insert medication;
             

         } catch (Exception e) {
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
         }

        // Redirect to new record if using salesforce classic 
        // return new PageReference('/'+newSP.id+'/e?retURL=%2F'+newSP.id);
        
        //Redirect to new record if using salesforce Lightning 
		return new PageReference('/one/one.app?#/sObject/'+newSP.id+'/view');
    }
    
}