src/objects/sked_Support_Plan__c.object
<CustomObject>
    <fields>
        <fullName>sked_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Support Plans</relationshipLabel>
        <relationshipName>sked_Support_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Plan</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Support Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/sked_Support_Plan_Comment__c.object
<CustomObject>
    <fields>
        <fullName>sked_Case_Comment__c</fullName>
        <label>Case Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sked_Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>sked_Edited_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Edited By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>sked_Support_Plan_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sked_Public__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sked_Support_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Plan</label>
        <referenceTo>sked_Support_Plan__c</referenceTo>
        <relationshipName>sked_Support_Plan_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sked_Updated_Date__c</fullName>
        <label>Updated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Support Plan Comment</label>
    <nameField>
        <displayFormat>SPC-{000000}</displayFormat>
        <label>Support Plan Comment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Plan Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sked_CarePlan_SupportNotesContoller.cls
public class sked_CarePlan_SupportNotesContoller {
	@AuraEnabled
    public static list<sked_Support_Plan_Comment__c> getSupportNotesFromCase(Id caseId) {
        system.debug('################################################# sked_CarePlan_SupportNotesContoller ##########################################');
        system.debug('########## params: caseId = ' + caseId);
        List<sked_Support_Plan__c> supportPlans = [select id from sked_Support_Plan__c where sked_Account__c = :caseId];
        if (supportPlans.isEmpty()) {
            system.debug('########## supportPlans is isEmpty');
            return new list<sked_Support_Plan_Comment__c>();
        }
        system.debug('########## supportPlans:' + supportPlans);

        list<sked_Support_Plan_Comment__c> supportPlanComments = [select id, sked_Case_Comment__c, sked_Comment__c, sked_Edited_By__c, sked_Public__c, sked_Support_Plan__c, sked_Updated_Date__c
                                                            from sked_Support_Plan_Comment__c 
                                                            where sked_Support_Plan__c IN :supportPlans
                                                            order by sked_Support_Plan__c];
        
        system.debug('########## supportPlanComments:' + supportPlanComments);
        
        system.debug('################################################# End sked_CarePlan_SupportNotesContoller #######################################');
        return supportPlanComments;
    }
}